FROM apache/superset:6.0.0-py312

USER root

RUN apt-get update && apt-get install -y \
  libpq-dev \
  gcc \
  && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | /app/.venv/bin/python3

COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir -e .[superset] 

USER superset

