FROM apache/superset:6.0.0

USER root

RUN apt-get update && apt-get install -y \
  libpq-dev \
  gcc \
  && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | /app/.venv/bin/python3

RUN python3 -m pip install --no-cache-dir psycopg2-binary redis clickhouse-connect

USER superset

