FROM apache/airflow:3.2.2-python3.12 AS base

ENV AIRFLOW_HOME=/opt/airflow
WORKDIR $AIRFLOW_HOME

COPY pyproject.toml uv.lock ./
COPY common/ common/
COPY etl/ etl/
COPY dags/ dags/
COPY sql/ sql/
COPY configs/ configs/
COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir -e .[airflow] 
ENV PYTHONPATH=$AIRFLOW_HOME

FROM base AS test

RUN pip install --no-cache-dir -e .[test]

COPY tests/ tests/

ENTRYPOINT ["pytest"]
CMD ["tests", "-v"]

FROM base AS production
