import os

REDIS_URL = os.getenv("REDIS_URL")
RATELIMIT_STORAGE_URI = f"{REDIS_URL}/0" 
SQLALCHEMY_DATABASE_URI = os.getenv("SUPERSET__SQLALCHEMY_DATABASE_URI")
SECRET_KEY = os.getenv("SUPERSET_SECRET_KEY")

CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 86400,
    "CACHE_KEY_PREFIX": "superset_results_",
    "CACHE_REDIS_URL": f"{REDIS_URL}/1"
}

FILTER_STATE_CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 900,
    "CACHE_KEY_PREFIX": "superset_filter_",
    "CACHE_REDIS_URL": f"{REDIS_URL}/2"
}

EXPLORE_FORM_DATA_CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 1800,
    "CACHE_KEY_PREFIX": "superset_explore_",
    "CACHE_REDIS_URL": f"{REDIS_URL}/3"
}
